### ISSUE TITLE
我在运行python calibration.py --config ./configs/sample.yaml时会报下面的错误，没找到解决的方法，请问您知道吗

### ISSUE THREAD

**Issue by carleft** [HViktorTsoi/ACSC#4]
Calculating frame: 0 / 21
Traceback (most recent call last):
  File "calibration.py", line 943, in <module>
    calibration(keep_list=None)
  File "calibration.py", line 873, in calibration
    corners_world, final_cost, corners_image = detection_result[idx].get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'module' object has no attribute 'PointCloud_PointXYZI'

**Comment by HViktorTsoi** [comment]
您好 请确定您安装了[pcl 1.8](https://askubuntu.com/questions/916260/how-to-install-point-cloud-library-v1-8-pcl-1-8-0-on-ubuntu-16-04-2-lts-for)， 以及[python-pcl](https://github.com/strawlab/python-pcl)

**Comment by caocheng1cc** [comment]
> Calculating frame: 0 / 21 Traceback (most recent call last): File "calibration.py", line 943, in calibration(keep_list=None) File "calibration.py", line 873, in calibration corners_world, final_cost, corners_image = detection_result[idx].get() File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get raise self._value AttributeError: 'module' object has no attribute 'PointCloud_PointXYZI'
请问你解决了这个问题吗，我也遇到了同样的问题，我的pcl版本是1.8.1，vtk是1.7.1
