### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by alsosos** [HViktorTsoi/ACSC#8]
用pyhton3 运行 python3 calibration.py --config ./configs/sample.yaml报错
Traceback (most recent call last):
  File "calibration.py", line 27, in <module>
    import segmentation_ext
ImportError: dynamic module does not define module export function (PyInit_segmentation_ext)
python2 运行python calibration.py --config ./configs/sample.yaml报错
Traceback (most recent call last):
  File "calibration.py", line 27, in <module>
    import segmentation_ext
ImportError: No module named segmentation_ext
请问怎么解决

**Comment by HViktorTsoi** [comment]
对于python3下的报错，请参考issue #1 的解决方案；

对于python2下的报错， 看起来您的segmentaion_ext是在python3的环境下编译安装的，如果要使用python2，还要在python2的环境重新编译安装一次
